---

name: windows10
cpus: 4
ram: 4G

# boot mode: False=BIOS, True=EFI. Default: False
efi: False

# boot menu. Default: False. 
# If menu is disabled, the boot disk is selected as follows:
#  in install mode: first boot from CD, on next reboot from HDD
#  in run mode: boot from first HDD in the 'disk' list
bootmenu: False

# disk image file or /dev/ file
disk: system.qcow2

# Alternative syntax to above
#
# disks:
#     - system.qcow2
#     - user_data.qcow2

# Use virtio-scsi for disk emulation?
# Applicable only to image file based disks
# Default=True
disk_virtio: True

# will mount these images in "install" mode
os_install:
    - Win10_21H2_English_x64.iso
    - virtio-win-0.1.217.iso

# USB Passthrough
#
# QEMU user must be able to rw the device:
# ---------------------------------------------
#  /etc/udev/rules.d/50-usbpassthrough.rules                                                                                                                                                                                                                                                 ~/vm/makemkv
# ---------------------------------------------
# SUBSYSTEM=="usb", ATTR{idVendor}=="xxxx", ATTR{idProduct}=="xxxx", MODE="0666"
#
# vendor:product
usb: 1234:5678


# Share a host directory with virtiofsd. 
# This method provides best performance as well as other useful virtualisation features.
# https://virtio-fs.gitlab.io/index.html
#
# On guest the directory can be mounted as:
#  sudo mount -t 9p -o trans=virtio,version=9p2000.L hostshare /mnt/share
share_dir_as_fsd: shared

# Map a host directory to a block dev with FAT fs on guest
#
# Never
# - use non-ASCII filenames 
# - write to the FAT directory on the host system while accessing it with the guest system
# https://www.qemu.org/docs/master/system/images.html#virtual-fat-disk-images
share_dir_as_fat: shared

# Add network interface.
# Default=True
nic: True

# True: use virtio-net-pci as NIC model
# False: use e1000 as NIC model
# Default=True
nic_virtio: True

# Forward local port 2222 to guest port 22
# Then, you can do :
#  ssh localhost -p 2222
nic_forward_ports:
    - host: 2222
      guest: 22


# SPICE port. Can be a number like 5900 or 'auto' to select a next non occupied port
# Default=auto
spice_port: auto
