---

name: windows10
cpus: 4
ram: 4G
disk: system.qcow2
spice_port: 5900

# Use virtio-scsi for disk emulation? Optional, default = True
disk_virtio: True

# also suppors variant:
#
# disks: 
#     - system.qcow2
#     - user_data.qcow2

# will mount these images in "install" mode
os_install:
    - Win10_21H2_English_x64.iso
    - virtio-win-0.1.217.iso


# vendor:product
usb: 1234:5678

# mount directory as virtual FAT filesystem
#
# Never
# - use non-ASCII filenames 
# - write to the FAT directory on the host system while accessing it with the guest system
# https://www.qemu.org/docs/master/system/images.html#virtual-fat-disk-images
ro_mount: shared
